project_id = "mwrahnkynhfulzkljeqs"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.ttsforfree]
verify_jwt = false

[functions.huggingface-tts]
verify_jwt = false

[functions.google-tts]
verify_jwt = false

[functions.google-cloud-tts]
verify_jwt = false

[functions.gemini-tts]
verify_jwt = false

[functions.gemini-cloud-tts]
verify_jwt = false

[functions.gemini-cloud-tts]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.generate-character-story]
verify_jwt = false
