project_id = "mwrahnkynhfulzkljeqs"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.ttsforfree]
verify_jwt = false

[functions.huggingface-tts]
verify_jwt = false

[functions.google-tts]
verify_jwt = false